#!/usr/bin/env python3
"""PVE Hardware Monitor API — auto-generated by installer"""
import http.server, json, struct, os, glob, subprocess, re
import sys, hmac, secrets, time, traceback, threading, concurrent.futures
from collections import defaultdict

PORT          = __PORT__
EC_PATH       = '/sys/kernel/debug/ec/ec0/io'
BOOST_PATH    = '__BOOST_PATH__'
BAT_PATH      = '__BAT_PATH__'
HW_CORETEMP   = '__HW_CORETEMP__'
HW_NVME       = '__HW_NVME__'
HW_PCH        = '__HW_PCH__'
HAS_EC        = __HAS_EC__
EC_FAN_REGS   = __EC_FAN_REGS__
HAS_BOOST     = __HAS_BOOST__
HAS_IPMI      = __HAS_IPMI__
IPMI_IFACE    = '__IPMI_INTERFACE__'
IPMI_HAS_FANS    = __IPMI_HAS_FANS__
IPMI_HAS_TEMPS   = __IPMI_HAS_TEMPS__
IPMI_HAS_POWER   = __IPMI_HAS_POWER__
IPMI_HAS_PSU     = __IPMI_HAS_PSU__
IPMI_HAS_VOLTAGE = __IPMI_HAS_VOLTAGE__
SYSTEM_MODEL  = '__SYSTEM_MODEL__'
BIOS_VER      = '__BIOS_VER__'
SDR_CACHE     = '/opt/pve-hwmonitor/sdr.cache'

# ── Security: token auth ─────────────────────────────────────────────
# Generated at install time by installer via secrets.token_hex(32)
API_TOKEN = os.environ.get('PVE_HWM_TOKEN', '__API_TOKEN__')

def _check_token(headers):
    """Constant-time comparison to prevent timing attacks."""
    provided = headers.get('X-Api-Token', '')
    if not API_TOKEN or API_TOKEN == '__API_TOKEN__':
        return True  # token not yet configured
    return hmac.compare_digest(provided.encode(), API_TOKEN.encode())

# ── Security: rate limiter (10 req/s per IP) ─────────────────────────
_rate_lock   = threading.Lock()
_rate_counts = defaultdict(lambda: [0, 0.0])  # ip -> [count, window_start]
RATE_LIMIT   = 10
RATE_WINDOW  = 1.0

def _rate_ok(ip):
    now = time.monotonic()
    with _rate_lock:
        count, start = _rate_counts[ip]
        if now - start > RATE_WINDOW:
            _rate_counts[ip] = [1, now]
            return True
        if count >= RATE_LIMIT:
            return False
        _rate_counts[ip][0] += 1
        return True

# ── Security: path validators ────────────────────────────────────────
SAFE_READ_PREFIXES  = ('/sys/', '/proc/', '/opt/pve-hwmonitor/', '/dev/')
ALLOWED_WRITE_PATHS = {BOOST_PATH} if BOOST_PATH else set()

def _safe_read_path(p):
    if not p: return False
    real = os.path.realpath(p)  # resolve symlinks before checking
    return any(real.startswith(px) for px in SAFE_READ_PREFIXES)

def _sdr_cache_valid():
    """Accept SDR cache only if root-owned and not group/world writable."""
    if not os.path.exists(SDR_CACHE): return False
    try:
        st = os.stat(SDR_CACHE)
        return st.st_uid == 0 and not (st.st_mode & 0o022)
    except OSError:
        return False

# ── Low-level helpers ────────────────────────────────────────────────

def read_ec(o, c=1):
    if not HAS_EC: return None
    try:
        with open(EC_PATH, 'rb') as f: f.seek(o); return f.read(c)
    except Exception:
        return None

def rf(p):
    if not _safe_read_path(p): return None
    try:
        with open(p) as f: return f.read().strip()
    except Exception:
        return None

def ri(p):
    v = rf(p)
    return int(v) if v and v.lstrip('-').isdigit() else None

def wf(p, v):
    if not p or p not in ALLOWED_WRITE_PATHS:
        return 'write to this path is not permitted'
    try:
        with open(p, 'w') as f: f.write(str(v)); return True
    except Exception:
        _log('wf', f'failed writing to {p}')
        return 'write failed'

def _log(ctx, msg):
    print(f'[ERROR] {ctx}: {msg}', flush=True)

def _log_exc(ctx):
    print(f'[ERROR] {ctx}:\n{traceback.format_exc()}', flush=True)

# ── hwmon helpers ────────────────────────────────────────────────────

def get_temps(hw_path, max_idx=16):
    if not hw_path: return []
    items = []
    for i in range(1, max_idx):
        t = ri(f'{hw_path}temp{i}_input')
        if t is None: continue
        lbl = rf(f'{hw_path}temp{i}_label') or f'Sensor {i}'
        items.append({'label': lbl, 'temp': round(t / 1000, 1)})
    return items

def get_fans_hwmon():
    fans = []
    for f in sorted(glob.glob('/sys/class/hwmon/hwmon*/fan*_input')):
        if not _safe_read_path(f): continue
        val = ri(f)
        if val is None: continue
        hwname = rf(os.path.join(os.path.dirname(f), 'name')) or '?'
        label  = rf(f.replace('_input', '_label')) or os.path.basename(f).replace('_input', '')
        fans.append({'name': f'{hwname}/{label}', 'rpm': val, 'source': 'hwmon'})
    return fans

def get_fans_ec():
    if not EC_FAN_REGS: return []
    fans = []
    for name, offset, duty_offset in [('CPU', 0x66, 0x97), ('GPU', 0x68, 0x98)]:
        raw_b  = read_ec(offset, 2)
        duty_b = read_ec(duty_offset)
        raw    = struct.unpack('<H', raw_b)[0] if raw_b else 0
        duty   = struct.unpack('B',  duty_b)[0] if duty_b else 0
        rpm    = round(2156250 / raw) if raw > 0 else 0
        fans.append({'name': name, 'rpm': rpm, 'raw': raw, 'duty': duty, 'source': 'ec'})
    return fans

# ── IPMI helpers ─────────────────────────────────────────────────────

def _ipmitool(*args, timeout=6):
    """Hard wall-clock timeout — frozen BMC never hangs the HTTP response."""
    if not HAS_IPMI: return []
    def _run():
        try:
            cmd = ['ipmitool', '-I', IPMI_IFACE, '-N', '3', '-R', '1']
            if _sdr_cache_valid():
                cmd += ['-S', SDR_CACHE]
            cmd += list(args)
            r = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout - 1)
            return r.stdout.splitlines() if r.returncode == 0 else []
        except Exception:
            return []
    try:
        with concurrent.futures.ThreadPoolExecutor(max_workers=1) as ex:
            return ex.submit(_run).result(timeout=timeout)
    except Exception:
        return []

def _parse_sdr_value(line):
    parts = [p.strip() for p in line.split('|')]
    if len(parts) < 3: return None
    name   = parts[0].strip()
    raw    = parts[1].strip()
    status = parts[2].strip().lower()
    m = re.match(r'^([\d.]+)\s*(.*)', raw)
    if not m: return None
    try:    val = float(m.group(1))
    except: return None
    return name, val, m.group(2).strip(), status

def get_ipmi_fans():
    if not IPMI_HAS_FANS: return []
    fans = []
    for line in _ipmitool('sdr', 'type', 'Fan'):
        r = _parse_sdr_value(line)
        if not r: continue
        name, val, unit, status = r
        if 'RPM' not in unit.upper(): continue
        fans.append({'name': name, 'rpm': int(val), 'status': status, 'source': 'ipmi'})
    return fans

def get_ipmi_temps():
    if not IPMI_HAS_TEMPS: return []
    temps = []
    for line in _ipmitool('sdr', 'type', 'Temperature'):
        r = _parse_sdr_value(line)
        if not r: continue
        name, val, unit, status = r
        if 'degrees' not in unit.lower() and '°' not in unit: continue
        if status in ('ns', 'na', 'n/a'): continue
        temps.append({'label': name, 'temp': round(val, 1), 'status': status})
    return temps

def get_ipmi_power():
    if not IPMI_HAS_POWER: return None
    result = {}
    for line in _ipmitool('dcmi', 'power', 'reading', timeout=6):
        line = line.strip()
        for pattern, key in [
            (r'Instantaneous power reading:\s+([\d.]+)\s+Watts', 'watts_now'),
            (r'Minimum.*?:\s+([\d.]+)\s+Watts',                  'watts_min'),
            (r'Maximum.*?:\s+([\d.]+)\s+Watts',                  'watts_max'),
            (r'Average.*?:\s+([\d.]+)\s+Watts',                  'watts_avg'),
        ]:
            m = re.search(pattern, line)
            if m: result[key] = float(m.group(1))
    return result if result else None

def get_ipmi_psu():
    if not IPMI_HAS_PSU: return []
    psus = []
    for line in _ipmitool('sdr', 'type', 'Power Supply'):
        r = _parse_sdr_value(line)
        if not r: continue
        name, val, unit, status = r
        psus.append({'name': name, 'value': val, 'unit': unit, 'status': status})
    return psus

def get_ipmi_voltages():
    if not IPMI_HAS_VOLTAGE: return []
    volts = []
    for line in _ipmitool('sdr', 'type', 'Voltage'):
        r = _parse_sdr_value(line)
        if not r: continue
        name, val, unit, status = r
        if status in ('ns', 'na', 'n/a'): continue
        volts.append({'label': name, 'value': round(val, 3), 'unit': unit, 'status': status})
    return volts

# ── Battery ──────────────────────────────────────────────────────────

def get_battery():
    if not BAT_PATH or not os.path.isdir(BAT_PATH): return None
    status   = rf(f'{BAT_PATH}/status')
    capacity = ri(f'{BAT_PATH}/capacity')
    e_now    = ri(f'{BAT_PATH}/energy_now')  or ri(f'{BAT_PATH}/charge_now')
    e_full   = ri(f'{BAT_PATH}/energy_full') or ri(f'{BAT_PATH}/charge_full')
    power    = ri(f'{BAT_PATH}/power_now')   or ri(f'{BAT_PATH}/current_now')
    voltage  = ri(f'{BAT_PATH}/voltage_now')
    cycles   = ri(f'{BAT_PATH}/cycle_count')
    return {
        'status':      status or 'Unknown',
        'capacity':    capacity,
        'energy_now':  round(e_now  / 1e6, 2) if e_now  else None,
        'energy_full': round(e_full / 1e6, 2) if e_full else None,
        'power':       round(power  / 1e6, 2) if power  else None,
        'voltage':     round(voltage/ 1e6, 2) if voltage else None,
        'cycles':      cycles,
    }

# ── System ───────────────────────────────────────────────────────────

def get_system():
    uptime = None
    try:
        with open('/proc/uptime') as f: uptime = float(f.read().split()[0])
    except Exception: pass
    load = None
    try:
        with open('/proc/loadavg') as f:
            p = f.read().split(); load = [float(p[0]), float(p[1]), float(p[2])]
    except Exception: pass
    mem = {}
    try:
        with open('/proc/meminfo') as f:
            for line in f:
                if   line.startswith('MemTotal:'):     mem['total']     = int(line.split()[1]) // 1024
                elif line.startswith('MemAvailable:'): mem['available'] = int(line.split()[1]) // 1024
    except Exception: pass
    if 'total' in mem and 'available' in mem:
        mem['used'] = mem['total'] - mem['available']
        mem['pct']  = round(mem['used'] / mem['total'] * 100, 1)
    return {'uptime_s': uptime, 'load': load, 'mem': mem}

# ── Main status builder ──────────────────────────────────────────────

def get_status():
    ec_temp_b  = read_ec(0x58)
    ec_temp    = struct.unpack('B', ec_temp_b)[0] if ec_temp_b else None
    board_b    = read_ec(0xC5)
    board_temp = struct.unpack('B', board_b)[0]   if board_b   else None

    coretemp_list = get_temps(HW_CORETEMP)
    pkg_temp      = coretemp_list[0]['temp'] if coretemp_list else ec_temp
    core_temps    = coretemp_list[1:] if len(coretemp_list) > 1 else []

    nvme = []
    for hw in sorted(glob.glob('/sys/class/hwmon/hwmon*/')):
        name = rf(hw + 'name') or ''
        if 'nvme' in name:
            for t in get_temps(hw):
                t['drive'] = hw.split('/')[-2]
                nvme.append(t)

    pch_list = get_temps(HW_PCH)
    pch_temp = pch_list[0]['temp'] if pch_list else None

    ipmi = None
    if HAS_IPMI:
        with concurrent.futures.ThreadPoolExecutor(max_workers=5) as ex:
            f_fans  = ex.submit(get_ipmi_fans)     if IPMI_HAS_FANS    else None
            f_temps = ex.submit(get_ipmi_temps)    if IPMI_HAS_TEMPS   else None
            f_power = ex.submit(get_ipmi_power)    if IPMI_HAS_POWER   else None
            f_psu   = ex.submit(get_ipmi_psu)      if IPMI_HAS_PSU     else None
            f_volts = ex.submit(get_ipmi_voltages) if IPMI_HAS_VOLTAGE else None
            def _get(fut, default):
                if fut is None: return default
                try: return fut.result(timeout=7)
                except Exception: return default
            ipmi_fans = _get(f_fans, [])
            ipmi = {
                'fans':     ipmi_fans,
                'temps':    _get(f_temps, []),
                'power':    _get(f_power, None),
                'psu':      _get(f_psu,   []),
                'voltages': _get(f_volts, []),
            }
    else:
        ipmi_fans = []

    fans_ec   = get_fans_ec()
    fans_hw   = get_fans_hwmon()
    fans_ipmi = ipmi_fans if ipmi else []
    if   fans_ec:   fans = fans_ec
    elif fans_hw:   fans = fans_hw
    elif fans_ipmi: fans = fans_ipmi
    else:           fans = []

    battery = get_battery()
    system  = get_system()

    boost_str = rf(BOOST_PATH) if HAS_BOOST else None
    bv = int(boost_str) if boost_str and boost_str.isdigit() else None

    return {
        'ok':         True,
        'model':      SYSTEM_MODEL,
        'cpu_temp':   pkg_temp,
        'core_temps': core_temps,
        'ec_temp':    ec_temp,
        'board_temp': board_temp,
        'pch_temp':   pch_temp,
        'nvme':       nvme,
        'fans':       fans,
        'battery':    battery,
        'system':     system,
        'ipmi':       ipmi,
        'has_ipmi':   HAS_IPMI,
        'mode':       {0:'normal',1:'boost',2:'silent'}.get(bv,'n/a') if bv is not None else 'n/a',
        'mode_raw':   bv,
        'has_boost':  HAS_BOOST,
    }

# ── HTTP server ──────────────────────────────────────────────────────

class Handler(http.server.BaseHTTPRequestHandler):

    def _client_ip(self):
        return self.client_address[0]

    def _cors(self):
        # Reflect request Origin instead of wildcard * — blocks cross-origin CSRF
        origin = self.headers.get('Origin', '')
        self.send_header('Access-Control-Allow-Origin', origin if origin else 'null')
        self.send_header('Access-Control-Allow-Methods', 'GET, POST, OPTIONS')
        self.send_header('Access-Control-Allow-Headers', 'Content-Type, X-Api-Token')
        self.send_header('Vary', 'Origin')

    def _sec(self):
        self.send_header('X-Content-Type-Options', 'nosniff')
        self.send_header('X-Frame-Options', 'DENY')
        self.send_header('Cache-Control', 'no-store')

    def _json(self, code, data):
        self.send_response(code)
        self.send_header('Content-Type', 'application/json')
        self._cors(); self._sec()
        self.end_headers()
        self.wfile.write(json.dumps(data).encode())

    def _rate_check(self):
        if not _rate_ok(self._client_ip()):
            self._json(429, {'ok': False, 'error': 'Too many requests'})
            return False
        return True

    def _auth_check(self):
        if not _check_token(self.headers):
            self._json(401, {'ok': False, 'error': 'Unauthorized'})
            return False
        return True

    def do_OPTIONS(self):
        self.send_response(204); self._cors(); self.end_headers()

    def do_GET(self):
        if not self._rate_check(): return
        if not self._auth_check(): return

        if self.path == '/api/status':
            try:
                self._json(200, get_status())
            except Exception:
                _log_exc('get_status')
                self._json(500, {'ok': False, 'error': 'Internal server error'})

        elif self.path in ('/', '/index.html'):
            try:
                self.send_response(200)
                self.send_header('Content-Type', 'text/html; charset=utf-8')
                self._sec()
                self.end_headers()
                dash = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'dashboard.html')
                with open(dash, 'rb') as f: self.wfile.write(f.read())
            except Exception:
                _log_exc('serve_dashboard')
                self._json(500, {'ok': False, 'error': 'Internal server error'})

        else:
            self._json(404, {'ok': False, 'error': 'Not found'})

    def do_POST(self):
        if not self._rate_check(): return
        if not self._auth_check(): return

        if self.path == '/api/mode' and HAS_BOOST:
            try:
                length = int(self.headers.get('Content-Length', 0))
                if length > 1024:
                    self._json(413, {'ok': False, 'error': 'Payload too large'}); return
                body = json.loads(self.rfile.read(length))
                mode = int(body.get('mode', -1))
                if mode not in (0, 1, 2):
                    self._json(400, {'ok': False, 'error': 'mode must be 0, 1, or 2'}); return
                names = {0: 'Normal', 1: 'Boost', 2: 'Silent'}
                res = wf(BOOST_PATH, str(mode))
                if res is True:
                    self._json(200, {'ok': True, 'msg': f'Fan profile: {names[mode]}'})
                else:
                    self._json(500, {'ok': False, 'error': 'Write failed'})
            except Exception:
                _log_exc('set_mode')
                self._json(500, {'ok': False, 'error': 'Internal server error'})
        else:
            self._json(404, {'ok': False, 'error': 'Not found or unavailable'})

    def log_message(self, *a): pass

    def handle_error(self, request, client_address):
        exc = sys.exc_info()[1]
        if isinstance(exc, (BrokenPipeError, ConnectionResetError)): return
        super().handle_error(request, client_address)

    def handle(self):
        try:
            super().handle()
        except (BrokenPipeError, ConnectionResetError):
            pass

# ── Start ────────────────────────────────────────────────────────────

auth_note = 'ENABLED' if (API_TOKEN and API_TOKEN != '__API_TOKEN__') else 'DISABLED (token not configured)'
print(f'PVE Hardware Monitor API on :{PORT}')
print(f'  Auth:      {auth_note}')
print(f'  Dashboard: http://0.0.0.0:{PORT}/')
http.server.HTTPServer(('0.0.0.0', PORT), Handler).serve_forever()
